embedding_size: 256
n_ui_layers: 2
n_layers: 1

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
reg_weight: 1e-04

knn_k: 10

learning_rate: 0.001

cl_loss: [0.01]
# lambda_psi: [100,200,300,400,500]

hyper_parameters: ["cl_loss"]
